### ISSUE TITLE
Mod not working on Linux

### ISSUE THREAD

**Issue by eOliverr** [Minecraft-Java-Edition-Speedrunning/mcsr-serversiderng-1.16.1#14]
### Version Information

7.0.0

### Expected Behavior

Getting a response about run submission after /seed etc. on linux

### Actual Behavior

When I open the game or create a new world with the mod enabled, I get errors in the log such as "Failed to create new RNGSession". Also when doing /seed there's no message about the run submission.  Log file with more details attached below.

### Reproduction Steps

Opening the game, creating a new world.

### System Information

> - Java Version: 19.0.2
> - CPU: Intel i5-12400F
> - GPU: AMD RX 6600
> - OS: Fedora Linux 37

### Other Information

Log file:
[log file.zip](https://github.com/Minecraft-Java-Edition-Speedrunning/mcsr-serversiderng-1.16.1/files/10844881/log.file.zip)
List of mods:
![Screenshot from 2023-02-28 00-41-41](https://user-images.githubusercontent.com/62429533/221702614-ea5ad0ce-170b-4424-893b-f80564f46dd0.png)

**Comment by VoidXWalker** [comment]
Fixed after #13
