### ISSUE TITLE
Crashes on startup with Java 8

### ISSUE THREAD

**Issue by SuperStormer** [Minecraft-Java-Edition-Speedrunning/mcsr-serversiderng-1.16.1#15]
### Version Information

> serverSideRNG-7.0.0.jar

### Expected Behavior

The game should load properly (as Java 8 is the default Java version for 1.16).

### Actual Behavior

The game crashes on startup: https://mclo.gs/alcMiEx

### Reproduction Steps

Attempt to load this mod with Java 8.

### System Information

> - Java Version: 1.8.0_292
> - CPU: n/a
> - GPU: n/a

### Other Information

This is the same bug as https://github.com/VoidXWalker/WorldPreview/issues/20, the same fix should work (https://github.com/VoidXWalker/WorldPreview/pull/23)

**Comment by LeeNeighoff** [comment]
Also having this issue with 9.0.0. Tried several Java 8 updates (361, 333, 311, 51) and did not see a change in behavior. Trying with Java 17 and skipping compatibility checks (Prism Launcher) allows the game to launch, but I'm not sure how stable the game will be (and whether it would affect verifiability of runs).

**Comment by tildejustin** [comment]
no point to keep this issue open as the mod is unfortunately essentially deprecated
